# Generated by Django 4.2.9 on 2024-01-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flower_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('wong', models.CharField(max_length=50)),
                ('sagun', models.CharField(max_length=50)),
                ('properties', models.TextField()),
                ('image', models.ImageField(upload_to='place_images/')),
            ],
        ),
    ]
